### ISSUE TITLE
Consulta que faz tabela temporária com e-mail e matrícula para login

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#100]

**Comment by LiraGui** [comment]
Elias Praciano ->  [Tabelas temporárias](https://elias.praciano.com/2015/04/como-criar-tabelas-temporarias-no-mysql/)

Imasters -> [Tabelas temporarias](https://imasters.com.br/data/mysql-e-tabelas-temporarias) com mysql

**Comment by LiraGui** [comment]
Mais sobre [tabelas temporárias](https://www.devmedia.com.br/forum/tabelas-temporarias-no-mysql/590995) na DevMedia.

**Comment by Pedrohsmarinho** [comment]
Post no StackOverFlow sobre tabelas tempórarias- [SQL- Tempórario](https://pt.stackoverflow.com/questions/115835/para-que-servem-as-tabelas-tempor%C3%A1rias)
