### ISSUE TITLE
Definir cores padrões do site

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#101]

**Comment by alinevenceslau** [comment]
Tons em verde que achamos interessante pra fazer parte do padrão do site: 


![Screenshot_20191107-215029](https://user-images.githubusercontent.com/43681132/68440097-b6217180-01a8-11ea-8902-4e0965d298e7.png)

![Screenshot_20191107-215403](https://user-images.githubusercontent.com/43681132/68440244-2cbe6f00-01a9-11ea-87bc-602adfb813f4.png)

**Comment by alinevenceslau** [comment]
Tons em verde e tons que harmonizam com verde que achamos interessante pra fazer parte do padrão do site: 

 Cor base - 59ff9e

![FOTO_20191107_220142](https://user-images.githubusercontent.com/43681132/68440736-be7aac00-01aa-11ea-834d-207cb932e6f0.jpg)

Cor base - 9bdb58

![FOTO_20191107_220208](https://user-images.githubusercontent.com/43681132/68440817-f550c200-01aa-11ea-85c5-c50b599e3fd8.jpg)

**Comment by alinevenceslau** [comment]
Usamos como base a cor 37bf8f (taranran).
