### ISSUE TITLE
Definir layout das telas

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#102]
Testar sites que ajudam na criação de telas e criar um layout padrão na que se sentir mais confortável.

**Comment by alinevenceslau** [comment]
Sites que talvez tenham layouts que sejam interessantes se basear (especificamente o 4) - [Site](https://www.viaagenciadigital.com.br/blog/exemplos-de-websites-criativos/amp/)

**Comment by RenissonSilva** [comment]
Sugestão de layout para home de aluno (Inacabada)
![HomeAluno](https://user-images.githubusercontent.com/40182898/68537951-6c24c100-034b-11ea-858d-500a33f9b43a.png)

**Comment by RenissonSilva** [comment]
Layout da home de aluno (com filtro)
![HomeAluno5](https://user-images.githubusercontent.com/40182898/68539473-2673f280-0363-11ea-9e7b-f9ef8f04bae2.png)
