### ISSUE TITLE
Criar back-end do filtro

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#107]
Eu **como** usuário **quero** um filtro **para** ver melhor os requerimentos.
- [x] Filtro para aluno
- [x] Filtro para funcionário

**Comment by LiraGui** [comment]
Reabrindo para corrigir bug.

**Comment by LiraGui** [comment]
Finalmente fechada

**Comment by lilialnas** [comment]
- [ ] Falha ao utilizar os filtros quando o usuário possui duas matrículas associadas. 
- [ ] Falha no filtro de situação na tela de requerimentos do funcionário.
- [ ] Ao clicar em "limpar filtros" na tela de listagem dos requerimentos do funcionário, o sistema está redirecionando para a tela de login.
