### ISSUE TITLE
Integração com o Google

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#11]
- [x] Estudar como se faz
- [ ] Testar a implementação

**Comment by gmatheus66** [comment]
Link Tutorial do Google OAuth com php [GOOGLE](https://cloud.google.com/php/getting-started/authenticate-users?hl=pt-br#deploying_the_app_to_the_app_engine_flexible_environment) [Documentação](https://github.com/googleapis/google-api-php-client)



Link Tutorial Autenticação OAuth com Laravel [Link](https://medium.com/employbl/add-login-with-google-to-your-laravel-app-d2205f01b895)

**Comment by gmatheus66** [comment]
Tutorial Login com Laravel 
[Medium](https://medium.com/employbl/add-login-with-google-to-your-laravel-app-d2205f01b895)

**Comment by gmatheus66** [comment]
Documentação Laravel com socialite
[Lara news](https://laravel-news.com/google-api-socialite)

**Comment by Pedrohsmarinho** [comment]
Login usando email google
[Sing in com google](https://laraveldaily.com/from-google-api-to-google-sign-in-with-laravel-socialite/)

**Comment by gmatheus66** [comment]
Tutorial Autenticação com Laravel
[Medium](https://medium.com/@confidenceiyke/laravel-5-8-google-socialite-authentication-a8b57aa59241)

Documentação do Google sobre OAuth
[Google](https://developers.google.com/identity/protocols/OAuth2?csw=1)
