### ISSUE TITLE
Melhorar front da index de requerimentos

### ISSUE THREAD

**Issue by LiraGui** [gmatheus66/reqon#117]
Eu **como** usuário **quero** uma tela organizada **para** facilitar a leitura e entendimento do que está sendo mostrado.

- [x] Centralizar texto na listagem
- [x] Deixar data em uma linha
- [x] Mudar pra text campo do input 'Protocolo'
- [x] Deixar os 2 inputs de data em baixo

**Comment by lilialnas** [comment]
Ajustes a serem implementados

- [ ] Tirar as bordas azul de alguns botões.
- [ ] A funcionalidade de "Limpar filtro" tá quase apagada no index.
- [ ] Filtro de "curso" deve ser a parte dos demais filtros que são padrões para usuários que só tem um curso.
