### ISSUE TITLE
Integração com o Facebook

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#12]
- [x] Estudar como se faz
- [ ] Testar a implementação

**Comment by LiraGui** [comment]
Links sobre SDK do Facebook para PHP:
Sobre a SDK:  https://developers.facebook.com/docs/reference/php/4.0.0?locale=pt_BR
Graph API: https://developers.facebook.com/docs/graph-api/overview/?locale=pt_BR
