### ISSUE TITLE
Expandir e colapsar as informações dos detalhes dos requerimentos

### ISSUE THREAD

**Issue by LiraGui** [gmatheus66/reqon#122]
eu **como** desenvolvedor **quero**  estudar colapsamento e expansão  utilizando o  javascript .

**Comment by jucielefernandes** [comment]
**Colapsamento** 
O plugin JavaScript collapse é usado para mostrar e esconder conteúdo. 

collapse - esconde o conteúdo.
collapsing - é aplicado durante a transição.
collapse.show - mostra o conteúdo.

- **collapse('toggle')**

Alterna um elemento colapsável para mostrar ou escondê-lo. Retorna ao invocador antes do elemento colapsável ter sido mostrado ou escondido, de fato (antes do evento shown.bs.collapse ou hidden.bs.collapse ocorrer).

- **collapse('show')**
Mostra um elemento colapsável. Retorna ao invocador antes do elemento colapsável ter sido mostrado, de fato (antes do evento shown.bs.collapse ocorrer).

- **collapse('hide')**
Esconde um elemento colapsável. Retorna ao invocar antes do elemento colapsável ter sido escondido, de fato (antes do evento hidden.bs.collapse ocorrer).

- **collapse('dispose')**
Destroi o colapso de um elemento.






**Link:** https://getbootstrap.com.br/docs/4.1/components/collapse/

**Comment by alinevenceslau** [comment]
Site que tem conteúdos interessantes sobre expandir e colapsar detalhes - [Site](https://www.w3schools.com/bootstrap/bootstrap_collapse.asp)
