### ISSUE TITLE
Alterar forma que mensagem de criação do requerimento aparece

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#123]
Eu **como** usuário **quero** que a mensagem apareça de forma clara **para** saber quando requerimento foi criado com sucesso

- [x] Modificar forma que mensagem de sucesso do requerimento aparece

**Comment by lilialnas** [comment]
@RenissonSilva sempre bom especificar como vai ser implementado a "forma clara" da issue, pois clareza pode ter várias interpretações.

**Comment by lilialnas** [comment]
Minha implementação de clareza:

- [x] O tom de verde deve ser mais suave ( está muito próximo da cor do site).
- [x] Permitir que o usuário possa fechar o alert da mensagem ( Requerimento criado com sucesso!)

**Comment by lilialnas** [comment]
- [ ] Acredito que devemos modificar a cor da mensagem ( talvez algum tom de cinza).
