### ISSUE TITLE
Criar layout das telas para aluno

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#126]
- [x] Criar tela da welcome

- [x]  Criar tela de detalhes de requerimento

- [x]  Criar tela de novo requerimento

**Comment by K0rgana** [comment]
sugestão de tela de detalhes do requerimento do aluno

![Captura de tela_2019-11-15_23-20-35](https://user-images.githubusercontent.com/48961500/68986507-c36cda80-07fe-11ea-8356-fd786dd88de9.png)

Versão 2
![Captura de tela_2019-11-15_23-59-09](https://user-images.githubusercontent.com/48961500/68987011-02515f00-0804-11ea-90e8-f08734983e80.png)

**Comment by K0rgana** [comment]
prototipação do layout da welcome está na issue #127

**Comment by K0rgana** [comment]
Sugestão de tela de novo requerimento
![image](https://user-images.githubusercontent.com/48961500/69012006-79473e80-094f-11ea-89d4-2395e30b4639.png)

Versão com anexo
![image](https://user-images.githubusercontent.com/48961500/69011982-413ffb80-094f-11ea-8a8d-4fdd7c64b12c.png)

**Comment by lilialnas** [comment]
![image](https://user-images.githubusercontent.com/45184669/69146962-b4f91a00-0aaf-11ea-9b2f-988d1fa73bad.png)
