### ISSUE TITLE
Criar front-end da tela welcome

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#127]
Eu **como** usuário **quero** uma tela organizada e bonita **para** conseguir entender do que se trata o site logo ao abrir e navegá-lo de forma fácil

- [x] Inserir navbar
- [x] Trocar imagem de fundo
- [x] Colocar principais características do site
- [x] Padronizar tela para usuário logado/não logado

**Comment by K0rgana** [comment]
![Captura de tela_2019-11-14_00-13-08](https://user-images.githubusercontent.com/48961500/68823791-a061ef80-0673-11ea-8986-c60fab252696.png)

[link para editar no figma](https://www.figma.com/file/RJkISYhKH3gBXjVC6CLeD2/Untitled?node-id=0%3A1)

[imagem de fundo usada](https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80)

**Comment by lilialnas** [comment]
- [x] Usar consistência e padronização na tela de welcome ( o mesmo padrão do usuário logado).
- [x] Não precisa de link/botão "Início", o logo do sistema deve fazer essa função.
