### ISSUE TITLE
Back-end Redirecionar requerimento para outro setor

### ISSUE THREAD

**Issue by gmatheus66** [gmatheus66/reqon#130]
Eu **como** Desenvolvedor **quero** fazer o backend **para** poder enviar o requerimento de um setor para o outro

- [x] Criar Rota
- [x] Criar método para salvar o redirecionamento

**Comment by lilialnas** [comment]
- [x] Realizar ajustes no fluxo do requerimento. 
- [x] Não pode encaminhar para o mesmo setor várias vezes.
- [x] O mesmo setor não pode encaminhar para seu próprio setor.
