### ISSUE TITLE
Estudo sobre Elasticsearch no Laravel

### ISSUE THREAD

**Issue by LiraGui** [gmatheus66/reqon#133]

**Comment by LiraGui** [comment]
Elastic search com laravel, no site da [Made With Love](https://madewithlove.be/how-to-integrate-elasticsearch-in-your-laravel-app-2019-edition/)

**Comment by gmatheus66** [comment]
Documentação do elastic search [Site](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-analyze.html)

**Comment by gmatheus66** [comment]
Instalação do elasticsearch no ubuntu [Site](https://tecadmin.net/setup-elasticsearch-on-ubuntu/)

**Comment by Pedrohsmarinho** [comment]
Mais um artigo de como usar elasticsearch com laravel-[ SIte](https://michaelstivala.com/learning-elasticsearch-with-laravel/)

**Comment by Pedrohsmarinho** [comment]
Elasticsearch com Laravel Scout-[Medium](https://medium.com/@samogorm/basic-search-functionality-with-elasticsearch-laravel-scout-6ac182c99cbf)

**Comment by LiraGui** [comment]
How to make Laravel and Elasticsearch become friends - [Medium](https://medium.com/@babenko.i.a/how-to-make-laravel-and-elasticsearch-become-friends-55ed7690331c)

**Comment by gmatheus66** [comment]
Laravel e elasticsearch [site](https://madewithlove.be/how-to-integrate-elasticsearch-in-your-laravel-app-2019-edition/)

**Comment by Pedrohsmarinho** [comment]
Video com conceitos básicos de laravel e elasticsearch [youtube](https://www.youtube.com/watch?v=I82Bty67E-w&t=5s)
