### ISSUE TITLE
Estudo do Modelo ER

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#14]
- [x] Analisar o modelo

**Comment by gmatheus66** [comment]
Links Para estudo de Auto relacionamento
[Link1 - Stackoverflow](https://pt.stackoverflow.com/questions/296556/representa%C3%A7%C3%A3o-do-auto-relacionamento-muitos-para-muitos#)

[Link2 - Stackoverflow](https://pt.stackoverflow.com/questions/8408/como-funciona-relação-entre-a-mesma-tabela)

[Link3- Stackoverflow ](https://pt.stackoverflow.com/questions/154898/auto-relacionamento-no-mysql)

[Link4- Stackoverflow ](https://pt.stackoverflow.com/questions/154898/auto-relacionamento-no-mysql)

[Link5 - Sites Google](https://sites.google.com/site/uniplibancodedados1/aulas/aula-9---auto-relacionamentos)

[Link6 - Stackoverflow](https://pt.stackoverflow.com/questions/154898/auto-relacionamento-no-mysql)

[Link7 - guj](https://www.guj.com.br/t/auto-relacionamento-mysql-resolvido/292609)

**Comment by gmatheus66** [comment]
![Captura de tela de 2019-09-23 21-52-42](https://user-images.githubusercontent.com/16937847/65473102-cd9cd900-de4c-11e9-8490-5ecbe5b6edad.png)

Imagem do modelo após algumas analises

**Comment by gmatheus66** [comment]
![image](https://user-images.githubusercontent.com/16937847/65601274-24eb9800-df78-11e9-9bc2-818f06017e65.png)


Adição da Tabela setor
