### ISSUE TITLE
Melhorar Front do login 

### ISSUE THREAD

**Issue by jucielefernandes** [gmatheus66/reqon#148]
Eu **como** usuário **quero** uma tela de login padronizada **para** manter a mesma paleta de cores do site e bonita

- [x] Tirar lembrar senha e esqueceu a senha 
- [x] Padronizar cor do layout

**Comment by Pedrohsmarinho** [comment]
Remoção de lembrar senha e esqueceu a senha feitas na issue #160 e #161 respectivamente.
