### ISSUE TITLE
Autenticação com digital

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#15]
- [x] Estudar [WebAuthn](https://webauthn.io/)

**Comment by RenissonSilva** [comment]
[Site oficial](https://webauthn.io/)
Exemplo de uso do WebAuthn - [github](https://github.com/lbuchs/WebAuthn)

**Comment by ranierivalenca** [comment]
O estudo foi realizado, mas terá uma baixa prioridade dentro do projeto.
