### ISSUE TITLE
Estudar CRUD  em Laravel

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#17]
- [x] Começar a estudar Laravel  
- [x] Fazer um CRUD em Laravel

**Comment by LiraGui** [comment]
Como criar um projeto em Laravel:
[Site do Laravel](https://laravel.com/docs/6.x)
[Site do Fedora](https://developer.fedoraproject.org/start/sw/web-app/laravel5.html)

**Comment by RenissonSilva** [comment]
Playlist explicando sobre criação de CRUD em laravel - [link](https://www.youtube.com/watch?v=EnkfyH1n4hI&list=PLsAVCHCFheVMTtLuV9_I8h19FHyV-rhFO&index=1)

CRUD criado - [link](https://github.com/RenissonSilva/crudLaravel)

**Comment by gmatheus66** [comment]
CRUD Criado - [Link](https://github.com/gmatheus66/crudlaravel)
