### ISSUE TITLE
Migrate no laravel

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#19]
- [x] Estudar como funciona o migrate
- [x] Desenvolver uma aplicação simples utilizando migrate

**Comment by LiraGui** [comment]
Links sobre Migration:
Site do Laravel -> https://laravel.com/docs/5.8/migrations
Imasters -> https://imasters.com.br/back-end/desenvolvendo-migrations-utilizando-laravel
Especializati -> https://blog.especializati.com.br/criar-tabelas-laravel-migrations/

**Comment by gmatheus66** [comment]
Link Sobre Models e Relacionamento:

[Medium](https://medium.com/trainingcenter/relacionando-models-e-tabelas-no-laravel-5-4-a8365a12eca2)

**Comment by RenissonSilva** [comment]
[Alterar Tabela com Migrations no Laravel sem Perder os Dados](https://blog.especializati.com.br/alterar-tabela-migrations-laravel-sem-perder-dados/)

**Comment by RenissonSilva** [comment]
Aplicação com migrate - [Github](https://github.com/RenissonSilva/crudLaravel)
