### ISSUE TITLE
SonarCloud

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#2]
Eu **como** Desenvolvedor **quero** analisar melhor os códigos **para** ter um desenvolvimento melhor e mais guiado.

- [x] Criar o Projeto no SonarCloud
- [x] Vincular SonarCloud ao repositório
- [x] Adicionar arquivo de Configuração

**Comment by gmatheus66** [comment]
Link para o Projeto no SonarCloud
[Projeto reqon](https://sonarcloud.io/dashboard?id=gmatheus66_reqon)
[Sobre o SonarCloud](https://sonarcloud.io/about)
