### ISSUE TITLE
Persona dos Alunos

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#23]
- [x] Criar persona dos alunos

**Comment by RenissonSilva** [comment]
Persona do aluno - [Link](https://docs.google.com/document/d/1oui-uRkTziE1HmJ5ftAVAR_mkiNjRxUnUzxdRfbT5WI/edit?usp=sharing)

Persona de exemplo(da professora Liliane) - [Link](https://docs.google.com/document/d/1R1tWT46FpGv2qXPbC7eK1Gqe5KzfvydO4q3ea6iio_k/edit?usp=sharing)

**Comment by lilialnas** [comment]
Realizei alguns ajustes na persona do aluno.
