### ISSUE TITLE
Adicionar mecanismo de autenticação

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#25]
Eu **como** desenvolvedor **quero** poder ter o método de autenticação **para** que os alunos consigam entrar nos seus perfis.

- [x] Adicionar APENAS opção de login (o cadastro será feito pelas seeds)

**Comment by RenissonSilva** [comment]
Autenticação padrão adicionada
_Falta_ modificar para logar baseado nas seeds
