### ISSUE TITLE
Popular tabelas de tipos e subtipos

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#29]
Eu **como** desenvolvedor **quero** popular tabelas de tipos e subtipos **para**manter as informações básicas de um requerimento.
- [x] Adicionar informações da tabela tipos
- [x] Adicionar informações da tabela subtipos

**Comment by LiraGui** [comment]
Link de como povoar tabelas com Seeder Laravel;
[Bill Guedes](https://www.billguedes.com.br/site/lembrete/laravel/popular-dados-predeterminados-no-laravel/)
[CodigoMania](http://www.codigomania.com.br/site/snip-uso-de-seed-no-laravel-17330)
[Laravel](https://laravel.com/docs/6.x/seeding)
