### ISSUE TITLE
Estudar importação para tabelas de estudantes e matrículas

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#30]
- [ ] Estudar API do Q-acadêmico
- [ ] Fazer teste com API do Q-acadêmico

**Comment by gmatheus66** [comment]
Sites Relacionados ao Q-acadêmico
[Qualidata](http://www2.qualidata.com.br/)
[Base sobre o sistema da qualidata](http://baseconhecimento.qualidata.com.br/)
[API do Moodle](https://docs.moodle.org/dev/Access_API)

**Comment by LiraGui** [comment]
Devido ao insucesso com as pesquisas para esta Spike, estaremos fechando a issue por causa de não conseguimos ter resultados com a pesquisa.
