### ISSUE TITLE
Estudar como popular tabelas

### ISSUE THREAD

**Issue by alinevenceslau** [gmatheus66/reqon#31]
- [x] Estudar SEED

**Comment by LiraGui** [comment]
Links sobre Seed no Laravel:
[Site do Laravel](https://laravel.com/docs/5.6/seeding)
[Especializa Blog](https://blog.especializati.com.br/seeders-no-laravel/)

**Comment by gmatheus66** [comment]
Tutorial Sobre SEED
[medium - link 1](https://medium.com/@jurgenbosch/laravel-advanced-database-seeding-51c475707d92)
[medium - link 2](https://medium.com/grevo-techblog/lavarel-migration-seeding-b093a68990cd)
[medium - link 3](https://medium.com/by-vinicius-reis/trabalhando-com-seeds-no-laravel-5-142829ddc32e)
