### ISSUE TITLE
Como Sonarcloud ignora pastas

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#32]
- [x] Estudar como o Sonarcloud ignora pastas

**Comment by Pedrohsmarinho** [comment]
Documentação que explica que é possível ignorara arquivos [Documentação do SonarCloud](https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/)

**Comment by Pedrohsmarinho** [comment]
Como executar o sonar.Exclusion- [Documentação Sonar.Exclusion](https://sonarcloud.io/documentation/analysis/analysis-parameters/)

**Comment by gmatheus66** [comment]
Exemplo do sonarcloud
[Link -1 ](https://github.com/monicahq/laravel-sabre/blob/master/sonar-project.properties)
[Tutorial - Sonarcloud](https://dev.to/jeromegamez/continuous-php-code-quality-with-sonarcloud-276i)

**Comment by gmatheus66** [comment]
Alguns arquivos podem ser ignorados pelas configurações do sonarcloud, os arquivos que serão ignorados, eles ajudarão a manter uma apresentação mais clean e com menos warning e erros.
