### ISSUE TITLE
Criar Front-end do Login de Alunos

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#33]
Eu **como** aluno **quero** ter a tela de login **para** poder me autenticar

- [x] Criar a tela de login
- [x] Conectar com o back-end

**Comment by Pedrohsmarinho** [comment]
Por enquanto usamos a mesma tela tanto para login de funcionario, quanto para alunos. por esse motivo não será feito nada nessa issue por enquanto.

**Comment by Pedrohsmarinho** [comment]
Mas por motivos de não saber se será feito isso mesmo, a issue permanece aberta.
