### ISSUE TITLE
Estudar como criar seed de forma autônoma

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#35]
Criar seed com : 
- [x] Nomes aleatórios
- [x] Números aleatórios para o CPF
- [x] E-mail aleatório
- [x] Data de nascimento aleatória

**Comment by RenissonSilva** [comment]
Documentação oficial - [Laravel](https://laravel.com/docs/6.x/seeding)
Dicas gerais sobre seed - [link](https://laraveldaily.com/10-tips-about-data-seeding-in-laravel/)

**Comment by LiraGui** [comment]
Inserindo dados iniciais automaticamente na base de dados com o Laravel:
[WEBIG](https://www.webig.pro.br/colocando-dados-automaticamente-no-base-de-dados-com-o-laravel/)

**Comment by RenissonSilva** [comment]
Documentação do faker - [Github](https://github.com/fzaninotto/Faker#formatters)

**Comment by RenissonSilva** [comment]
**Implementação de teste** 
Criação de uma factory para gerar Users com name, birth-date, cpf e senha aleatórios - [Github](https://github.com/RenissonSilva/reqon_Testes)
