### ISSUE TITLE
Protótipo da tela dummy (form de quando está logado)

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#37]
- [x] Criar protótipo

**Comment by alinevenceslau** [comment]
Prototipação da tela dummy - 
[protipo_dummy1.zip](https://github.com/gmatheus66/reqon/files/3674192/protipo_dummy1.zip)

**Comment by ranierivalenca** [comment]
Não conseguimos ver esse protótipo

**Comment by alinevenceslau** [comment]
[Prototipo.zip](https://github.com/gmatheus66/reqon/files/3746135/Prototipo.zip)

**Comment by alinevenceslau** [comment]
[Prototipo.zip](https://github.com/gmatheus66/reqon/files/3746140/Prototipo.zip)

**Comment by ranierivalenca** [comment]
Acho que nas telas de requerimento seria legal um breadcrumb, pra melhorar a experiência do usuário.

**Comment by lilialnas** [comment]
Seguem alguns comentários do protótipo para serem ajustados na versão final. Não precisa corrigir o protótipo.
- [ ] Adicionar texto informando que a tela se trata de "Meus requerimentos".
- [ ] O botão de [Pesquisar] deve permanecer na tela, mas teremos que adicionar filtros para esta listagem de requerimento. Exemplo: Filtro por tipo, data de início e data de fim, situação etc.
- [ ] Adicionar botão de "Visualizar" o requerimento ou outras ações com o requerimento. 
DÚVIDA: Será possível cancelar um requerimento?
- [ ] Ao clicar no requerimento ( ação de visualizar o conteúdo do requerimento), colocar um breadcrumbs para que o usuário possa voltar para a lista de "Meus requerimentos"
- [ ] Na funcionalidade de "alterar senha", adicionar um botão de [Cancelar] para que o usuário possa desistir da ação.
- [ ] Ao alterar a senha, o sistema deve direcionar para a tela de dados básicos do usuário ( não precisa de uma tela para informar que a senha foi alterada com sucesso).
