### ISSUE TITLE
Back-end do Login

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#41]
- [x] Estudar como fazer Login com múltiplas Tabelas

**Comment by gmatheus66** [comment]
Login Com multiplas Tabelas 
Lara 5.2
[Medium](https://medium.com/@daluamon/multipla-autentica%C3%A7%C3%A3o-laravel-32711ca9bced)
Lara 5.4
[Medium](https://medium.com/@sayhicoelho/laravel-5-4-trabalhando-com-autentica%C3%A7%C3%B5es-independentes-sem-packages-adicionais-6e50c11a0b79)

**Comment by gmatheus66** [comment]
Video Tutorial sobre Multiplos Login
[youtube - en](https://www.youtube.com/watch?v=iKRLrJXNN4M)

**Comment by gmatheus66** [comment]
Login com multiples roles(papeis) 
[Medium - link1](https://medium.com/@sammynigwe/multiple-auth-scope-for-different-roles-laravel-5-8-a68cf30be663)
Multiples guards auth
[Medium - link2](https://medium.com/@sagarmaheshwary31/laravel-multiple-guards-authentication-setup-and-login-2761564da986)
