### ISSUE TITLE
Front do login de funcionário

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#43]
Eu **como** servidor **quero** ter a tela de autenticação **para** poder gerenciar os requerimentos

- [x] Criar a tela baseado no protótipo
- [x] Conectar com o back-end

**Comment by Pedrohsmarinho** [comment]
Por enquanto usamos a mesma tela tanto para login de funcionário, quanto para alunos. por esse motivo não será feito nada nessa issue.

**Comment by Pedrohsmarinho** [comment]
Mas, por motivos de não saber se será feito isso mesmo, a issue permanece aberta.

**Comment by ranierivalenca** [comment]
Não temos um login de funcionário =)
