### ISSUE TITLE
Popular a Tabela Matricula

### ISSUE THREAD

**Issue by gmatheus66** [gmatheus66/reqon#45]
Eu **como** Desenvolvedor **quero** popular a tabela Matricula **para** ter informacoes como base para o sistema

- [x] Popular a Tabela Matricula

**Comment by LiraGui** [comment]
Fechando Issue pois ouve duplicação da mesma.

**Comment by LiraGui** [comment]
Abrindo Issue para modificar código da Factory para otimizar geração de dados.
