### ISSUE TITLE
Estudar sobre views

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#52]
- [x] Estudar como manipular views

**Comment by RenissonSilva** [comment]
Documentação oficial - [Laravel](https://laravel.com/docs/6.x/views)

**Comment by RenissonSilva** [comment]
Explicando sobre template, renderização JSON, alias, loop, etc - [Especializati](https://blog.especializati.com.br/laravel-blade/)

**Comment by gmatheus66** [comment]
Explicação sobre blade 
[Medium](https://medium.com/@mjcoder/laravel-5-7-blade-layout-files-d774cc317c1b)

**Comment by LiraGui** [comment]
Mais sobre view no [Tutorials Point](https://www.tutorialspoint.com/laravel/laravel_views.htm).

**Comment by RenissonSilva** [comment]
Passando múltiplas variáveis na view - [link](https://www.easylaravelbook.com/blog/passing-multiple-variables-into-a-laravel-5-view/)
