### ISSUE TITLE
Criar back-end do login de funcionário

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#54]
Eu **como** desenvolvedor **quero** criar o backend de login **para** o funcionário poder analisar os requerimentos criados.

- [x] Criar o backend

**Comment by LiraGui** [comment]
[Sessão](https://blog.especializati.com.br/aprenda-como-utilizar-sessoes-no-laravel/) no laravel

**Comment by gmatheus66** [comment]
698
