### ISSUE TITLE
Criar back-end para estudante escolher o curso

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#67]
Eu **como** desenvolvedor **quero** colocar a funcionalidade de escolher o curso **para** que os alunos que tem mais de uma matrícula possam selecionar

-  [x] selecionar os cursos que o aluno está matriculado

**Comment by gmatheus66** [comment]
Uma parte do Codigo também esta incluído na issue GH-71 por se tratar de coisas muito proximas.
