### ISSUE TITLE
Back-end da listagem de requerimentos do funcionário

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#69]
Eu **como** desenvolvedor **quero** criar o back da listagem **para** poder listar todos os requerimentos que foram direcionados ao funcionário ou setor

- [x] selecionar todos os requerimentos de um funcionário

**Comment by LiraGui** [comment]
[Multipla Autenticação](https://medium.com/@daluamon/multipla-autentica%C3%A7%C3%A3o-laravel-32711ca9bced), no site da Medium.
