### ISSUE TITLE
Front-end da listagem de requerimentos do funcionário

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#70]
Eu **como** usuário **quero** uma tela onde possa ver todos os requerimentos **para** poder gerencia-los 

- [x] criar a view
- [x] criar a model
- [x] criar a rota 
- [x] mostrar requerimentos direcionados ao funcionário logado

**Comment by ranierivalenca** [comment]
Como a lista está pronta se o funcionário não pode logar?
