### ISSUE TITLE
Questionário

### ISSUE THREAD

**Issue by gmatheus66** [gmatheus66/reqon#8]
- [x] Elaborar as perguntas
- [x] Dividir as perguntas por tipo de usuário(Aluno, Professor/Coordenador e CRADT)
- [x] Criar o formulário no google forms.
- [x] Divulgação do link

**Comment by lilialnas** [comment]
Deixa o link do google form aqui para analisar ( mesmo que ainda  esteja em construção).

**Comment by alinevenceslau** [comment]
Link referente ao questionário de professores:
[Questionário](https://docs.google.com/forms/d/e/1FAIpQLSfthZWvTj3AUAP8uhg5GryE45wA-yQUa8kfB-0TY46jUWe4bg/viewform)

**Comment by gmatheus66** [comment]
**Fechado** Link referente ao Questionário para os Alunos 
[Questionário](https://docs.google.com/forms/d/e/1FAIpQLSecdli_RI3INMLyeu9ExuE_K_ZdgAMg-ogqA0JTebdTmWKi6Q/viewform?usp=sf_link)

**Comment by alinevenceslau** [comment]
**Fechado** Link referente ao Questionário para os coordenadores:
[Questionário](https://docs.google.com/forms/d/e/1FAIpQLSdFqTE56zySaPxlYiIYLrIaFw4QwdajERrZRTFjptt_uYi4gA/viewform)
