### ISSUE TITLE
Estudar Docker

### ISSUE THREAD

**Issue by gmatheus66** [gmatheus66/reqon#87]
Estudar Docker para uma possível implantação no sistema.

- [x] Estudar Docker

**Comment by gmatheus66** [comment]
Link explicando o que é Docker e como começar
[Medium](https://medium.com/trainingcenter/docker-o-que-%C3%A9-docker-e-como-come%C3%A7ar-58e04bdcb043)

**Comment by LiraGui** [comment]
Como instalar o Docker
[Doc](https://docs.docker.com/install/linux/docker-ce/fedora/)

**Comment by RenissonSilva** [comment]
Como construir uma aplicação com docker - [GeekHunter](https://www.google.com/amp/s/blog.geekhunter.com.br/docker-na-pratica-como-construir-uma-aplicacao/amp/)

**Comment by gmatheus66** [comment]
Tutorial de instalação e configuração básica do docker 
[Digital Ocean](https://www.digitalocean.com/community/tutorials/como-instalar-e-usar-o-docker-no-ubuntu-18-04-pt)

**Comment by alinevenceslau** [comment]
Link explicando o que é o docker e como funciona - [Docker] (https://docker-curriculum.com/)

**Comment by Pedrohsmarinho** [comment]
Link da documentação da utilização de imagens com o Doker - [Docker Image ](https://docs.docker.com/engine/reference/commandline/images/)
