### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by gmatheus66** [gmatheus66/reqon#9]
- [x] Elaborar o roteiro
- [x] Marcar um horário com os funcionários da CRADT
- [x] Documentar as sugestões dadas no google sheets

**Comment by lilialnas** [comment]
Deixa aqui o link do roteiro ( mesmo que incompleto ainda).

**Comment by alinevenceslau** [comment]
Link relativo ao roteiro do Brainstorming:
[Roteiro](https://docs.google.com/document/d/1H55U-gP8g6cZQ7OQWyfLiIBWg4EkdpjSJ3rjBAkiyCw/edit?usp=sharing)

**Comment by alinevenceslau** [comment]
Arquivo atualizado com as respostas do brainstorming.
