### ISSUE TITLE
Criar front-end dos detalhes do requerimento

### ISSUE THREAD

**Issue by RenissonSilva** [gmatheus66/reqon#91]
Eu **como** Usuario **quero** ver os detalhes do requerimento **para** ter mais informações sobre o requerimento que selecionei

- [x] Criar view
- [x] Mostrar os detalhes do requerimento

**Comment by lilialnas** [comment]
Ajustes precisam ser feitos
 - [x] Opção de voltar para a listagem de requerimentos após o detalhamento. Aconselho o uso de Breadcrumbs.
- [x] Apresentar mais detalhes do requerimento com histórico da movimentação.

**Comment by gmatheus66** [comment]
A Implementação dos BreadCrumbs esta na issue GH-103
